/** Public deterministic helpers for Plugin contract testing. */

export {
    createControlledImageDecoder,
    createDeferredOperation,
    type ControlledImageDecoder,
    type DeferredOperation,
} from './deferred-operation.js';
export { createPluginTestFabric, type PluginTestFabric } from './fabric-test-harness.js';
export {
    createPluginTestHost,
    type PluginTestCapabilityProvider,
    type PluginTestHost,
    type PluginTestHostOptions,
    type PluginTestHostState,
} from './plugin-test-host.js';
export {
    CONFORMANCE_PROFILE,
    assertInstallRollback,
    assertLifecycleOrder,
    assertMissingCapabilityFailure,
    assertNoLeakedRegistrations,
    assertOptionalCapabilityFallback,
    assertPermissionDeclarationMatchesUsage,
    assertPersistentKindCodecCoverage,
    assertStateRoundTrip,
    assertTypeInferenceFixtures,
    runPluginConformance,
    type ConformanceAssertionResult,
    type ConformanceAssertionStatus,
    type PersistentKindContract,
    type PersistentKindInspection,
    type PluginAssertionOptions,
    type PluginConformanceOptions,
    type PluginConformanceReport,
    type PluginFactory,
    type StateRoundTripAdapter,
} from './plugin-conformance.js';
export {
    assertBaseImageInvariant,
    assertBundleIsolation,
    assertCompoundTransaction,
    assertNoUndeclaredFabricGlobalMutation,
    assertOverlayMutationHistory,
    assertPackageDoesNotBundleCoreOrFabric,
    assertPeerDependencyContract,
    assertSliceMigration,
    assertStrongMultiInstanceIsolation,
    captureFabricGlobalState,
    type BaseImageInvariantAttempt,
    type BaseImageInvariantObservation,
    type BundleIsolationObservation,
    type CompoundTransactionObservation,
    type FabricGlobalMutationLifecycle,
    type MultiInstanceObservation,
    type OverlayMutationHistoryObservation,
    type PackageModuleObservation,
    type PeerDependencyManifest,
    type ResponsibilityAssertionOptions,
    type SliceMigrationObservation,
} from './responsibility-assertions.js';
